# Form implementation generated from reading ui file './uic.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import pathlib
from PyQt6 import QtCore, QtGui, QtWidgets
from .widgets import InputWithAction


class UiMainWindow(object):
    FILE_PATH = pathlib.Path(os.path.dirname(os.path.abspath(__file__))).as_posix()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: #21252b;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_content_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.main_content_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_content_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_content_frame.setObjectName("main_content_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.main_content_frame)
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.side_contents = QtWidgets.QFrame(parent=self.main_content_frame)
        self.side_contents.setMinimumSize(QtCore.QSize(250, 0))
        self.side_contents.setMaximumSize(QtCore.QSize(250, 16777215))
        self.side_contents.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.side_contents.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.side_contents.setObjectName("side_contents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.side_contents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.side_header = QtWidgets.QFrame(parent=self.side_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_header.sizePolicy().hasHeightForWidth())
        self.side_header.setSizePolicy(sizePolicy)
        self.side_header.setMinimumSize(QtCore.QSize(0, 36))
        self.side_header.setMaximumSize(QtCore.QSize(16777215, 36))
        self.side_header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.side_header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.side_header.setObjectName("side_header")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.side_header)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.login = QtWidgets.QPushButton(parent=self.side_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login.sizePolicy().hasHeightForWidth())
        self.login.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.login.setFont(font)
        self.login.setStyleSheet("QPushButton {\n"
"    border-radius: 6px;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #ffffff, stop:1 #f6eeff);\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #3a925e, stop:1 #317c4f);\n"
"    border: 2px solid #0d3614;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #5dbe70, stop:1 #7bcf88);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #316849, stop:1 #315a43);\n"
"}")
        self.login.setObjectName("login")
        self.horizontalLayout_4.addWidget(self.login)
        self.logged_user = QtWidgets.QLabel(parent=self.side_header)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.logged_user.setFont(font)
        self.logged_user.setStyleSheet("background-color: #282c34;\n"
"color: #c5c9d8;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"border-radius: 7px;")
        self.logged_user.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logged_user.setObjectName("logged_user")
        self.horizontalLayout_4.addWidget(self.logged_user)
        self.verticalLayout_3.addWidget(self.side_header)
        self.online_users_frame = QtWidgets.QFrame(parent=self.side_contents)
        self.online_users_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.online_users_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.online_users_frame.setObjectName("online_users_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.online_users_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.online_users_container = QtWidgets.QFrame(parent=self.online_users_frame)
        self.online_users_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.online_users_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.online_users_container.setObjectName("online_users_container")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.online_users_container)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.online_users = QtWidgets.QListWidget(parent=self.online_users_container)
        self.online_users.setStyleSheet("background-color: #282c34;\n"
"color: #c5c9d8;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"border-radius: 7px;")
        self.online_users.setObjectName("online_users")
        self.verticalLayout_9.addWidget(self.online_users)
        self.verticalLayout_6.addWidget(self.online_users_container)
        self.verticalLayout_3.addWidget(self.online_users_frame)
        self.debug_info_frame = QtWidgets.QFrame(parent=self.side_contents)
        self.debug_info_frame.setMinimumSize(QtCore.QSize(0, 51))
        self.debug_info_frame.setMaximumSize(QtCore.QSize(16777215, 97))
        self.debug_info_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.debug_info_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.debug_info_frame.setObjectName("debug_info_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.debug_info_frame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.debug_info = QtWidgets.QFrame(parent=self.debug_info_frame)
        self.debug_info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.debug_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.debug_info.setObjectName("debug_info")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.debug_info)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.session_key = QtWidgets.QTextBrowser(parent=self.debug_info)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.session_key.setFont(font)
        self.session_key.setStyleSheet("background-color: #282c34;\n"
"color: #c5c9d8;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"border-radius: 7px;")
        self.session_key.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.session_key.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.session_key.setObjectName("session_key")
        self.verticalLayout_8.addWidget(self.session_key)
        self.hash = QtWidgets.QTextEdit(parent=self.debug_info)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.hash.setFont(font)
        self.hash.setStyleSheet("background-color: #282c34;\n"
"color: #c5c9d8;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"border-radius: 7px;")
        self.hash.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.hash.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.hash.setObjectName("hash")
        self.verticalLayout_8.addWidget(self.hash)
        self.verticalLayout_7.addWidget(self.debug_info)
        self.verticalLayout_3.addWidget(self.debug_info_frame)
        self.horizontalLayout_5.addWidget(self.side_contents)
        self.main_contents = QtWidgets.QFrame(parent=self.main_content_frame)
        self.main_contents.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_contents.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_contents.setObjectName("main_contents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_contents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(parent=self.main_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMinimumSize(QtCore.QSize(0, 36))
        self.header.setMaximumSize(QtCore.QSize(16777215, 36))
        self.header.setStyleSheet("QPushButton {\n"
"    border-radius: 6px;\n"
"    background-color: #21252b;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #5dbe70, stop:1 #7bcf88);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #316849, stop:1 #315a43);\n"
"}")
        self.header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.header_left = QtWidgets.QFrame(parent=self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_left.sizePolicy().hasHeightForWidth())
        self.header_left.setSizePolicy(sizePolicy)
        self.header_left.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header_left.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header_left.setObjectName("header_left")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.header_left)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.menu = QtWidgets.QPushButton(parent=self.header_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setMinimumSize(QtCore.QSize(28, 29))
        self.menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(f"{self.FILE_PATH}/icons/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu.setIcon(icon)
        self.menu.setIconSize(QtCore.QSize(24, 24))
        self.menu.setObjectName("menu")
        self.horizontalLayout_7.addWidget(self.menu)
        self.status_icon = QtWidgets.QLabel(parent=self.header_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_icon.sizePolicy().hasHeightForWidth())
        self.status_icon.setSizePolicy(sizePolicy)
        self.status_icon.setMinimumSize(QtCore.QSize(24, 24))
        self.status_icon.setAutoFillBackground(False)
        self.status_icon.setStyleSheet(f"background-image: url({self.FILE_PATH}/icons/offline.png);\n"
"background-position: center;\n"
"")
        self.status_icon.setText("")
        self.status_icon.setScaledContents(True)
        self.status_icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.status_icon.setWordWrap(False)
        self.status_icon.setObjectName("status_icon")
        self.horizontalLayout_7.addWidget(self.status_icon)
        self.status_text = QtWidgets.QLabel(parent=self.header_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_text.sizePolicy().hasHeightForWidth())
        self.status_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.status_text.setFont(font)
        self.status_text.setStyleSheet("background-color: #282c34;\n"
"color: #c5c9d8;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"border-radius: 7px;")
        self.status_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.status_text.setObjectName("status_text")
        self.horizontalLayout_7.addWidget(self.status_text)
        self.horizontalLayout_3.addWidget(self.header_left, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.header_right = QtWidgets.QFrame(parent=self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_right.sizePolicy().hasHeightForWidth())
        self.header_right.setSizePolicy(sizePolicy)
        self.header_right.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header_right.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header_right.setObjectName("header_right")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.header_right)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.minimize = QtWidgets.QPushButton(parent=self.header_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimize.sizePolicy().hasHeightForWidth())
        self.minimize.setSizePolicy(sizePolicy)
        self.minimize.setMinimumSize(QtCore.QSize(28, 29))
        self.minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(f"{self.FILE_PATH}/icons/hide.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimize.setIcon(icon1)
        self.minimize.setIconSize(QtCore.QSize(24, 24))
        self.minimize.setObjectName("minimize")
        self.horizontalLayout_6.addWidget(self.minimize)
        self.maximize = QtWidgets.QPushButton(parent=self.header_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maximize.sizePolicy().hasHeightForWidth())
        self.maximize.setSizePolicy(sizePolicy)
        self.maximize.setMinimumSize(QtCore.QSize(28, 29))
        self.maximize.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(f"{self.FILE_PATH}/icons/maximize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.maximize.setIcon(icon2)
        self.maximize.setIconSize(QtCore.QSize(24, 24))
        self.maximize.setObjectName("maximize")
        self.horizontalLayout_6.addWidget(self.maximize)
        self.close_button = QtWidgets.QPushButton(parent=self.header_right)
        self.close_button.setMinimumSize(QtCore.QSize(28, 29))
        self.close_button.setStyleSheet("QPushButton {\n"
"    border-radius: 6px;\n"
"    background-color: #21252b;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(243, 5, 5);\n"
"}\n"
"QPushButton:pressed {\n"
"       background-color: rgb(163, 15, 15);\n"
"}")
        self.close_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(f"{self.FILE_PATH}/icons/close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close_button.setIcon(icon3)
        self.close_button.setIconSize(QtCore.QSize(24, 24))
        self.close_button.setObjectName("close")
        self.horizontalLayout_6.addWidget(self.close_button)
        self.horizontalLayout_3.addWidget(self.header_right, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout.addWidget(self.header)
        self.messages_frame = QtWidgets.QFrame(parent=self.main_contents)
        self.messages_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.messages_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.messages_frame.setObjectName("messages_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.messages_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.messages_list_frame = QtWidgets.QFrame(parent=self.messages_frame)
        self.messages_list_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.messages_list_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.messages_list_frame.setObjectName("messages")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.messages_list_frame)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.messages = QtWidgets.QListWidget(parent=self.messages_list_frame)
        self.messages.setStyleSheet("background-color: #282c34;\n"
"color: #c5c9d8;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"border-radius: 7px;")
        self.messages.setObjectName("messages_list")
        self.verticalLayout_10.addWidget(self.messages)
        self.verticalLayout_4.addWidget(self.messages)
        self.verticalLayout.addWidget(self.messages_frame)
        self.new_message_frame = QtWidgets.QFrame(parent=self.main_contents)
        self.new_message_frame.setMinimumSize(QtCore.QSize(337, 51))
        self.new_message_frame.setMaximumSize(QtCore.QSize(16777215, 97))
        self.new_message_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.new_message_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.new_message_frame.setObjectName("new_message_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.new_message_frame)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.new_message_container = QtWidgets.QFrame(parent=self.new_message_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_message_container.sizePolicy().hasHeightForWidth())
        self.new_message_container.setSizePolicy(sizePolicy)
        self.new_message_container.setMinimumSize(QtCore.QSize(0, 0))
        self.new_message_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.new_message_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.new_message_container.setObjectName("new_message_container")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.new_message_container)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.new_message = InputWithAction(self.new_message_container, self.send)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_message.sizePolicy().hasHeightForWidth())
        self.new_message.setSizePolicy(sizePolicy)
        self.new_message.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.new_message.setFont(font)
        self.new_message.setStyleSheet("background-color: #282c34;\n"
"color: #c5c9d8;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"border-radius: 7px;")
        self.new_message.setPlainText("")
        self.new_message.setObjectName("new_message")
        self.verticalLayout_5.addWidget(self.new_message)
        self.horizontalLayout_2.addWidget(self.new_message_container)
        self.actions_frame = QtWidgets.QFrame(parent=self.new_message_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actions_frame.sizePolicy().hasHeightForWidth())
        self.actions_frame.setSizePolicy(sizePolicy)
        self.actions_frame.setStyleSheet("QPushButton {\n"
"    border-radius: 6px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 5px;\n"
"    padding-bottom: 5px;\n"
"    color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #ffffff, stop:1 #f6eeff);\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #3a925e, stop:1 #317c4f);\n"
"    border: 2px solid #0d3614;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #5dbe70, stop:1 #7bcf88);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #316849, stop:1 #315a43);\n"
"}")
        self.actions_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.actions_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.actions_frame.setObjectName("actions_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.actions_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.send_button = QtWidgets.QPushButton(parent=self.actions_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_button.sizePolicy().hasHeightForWidth())
        self.send_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.send_button.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(f"{self.FILE_PATH}/icons/send.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.send_button.setIcon(icon4)
        self.send_button.setObjectName("send")
        self.verticalLayout_2.addWidget(self.send_button)
        self.get_hash = QtWidgets.QPushButton(parent=self.actions_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_hash.sizePolicy().hasHeightForWidth())
        self.online_users.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.online_users.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.messages.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.messages.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.get_hash.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.get_hash.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(f"{self.FILE_PATH}/icons/hash.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.get_hash.setIcon(icon5)
        self.get_hash.setObjectName("get_hash")
        self.verticalLayout_2.addWidget(self.get_hash)
        self.horizontalLayout_2.addWidget(self.actions_frame)
        self.verticalLayout.addWidget(self.new_message_frame)
        self.horizontalLayout_5.addWidget(self.main_contents)
        self.horizontalLayout.addWidget(self.main_content_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login.setText(_translate("MainWindow", "LOGIN"))
        self.logged_user.setText(_translate("MainWindow", "UNAUTHORIZED"))
        self.session_key.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.status_text.setText(_translate("MainWindow", "OFFLINE"))
        self.new_message.setPlaceholderText(_translate("MainWindow", "Type your message here..."))
        self.send_button.setText(_translate("MainWindow", "  SEND"))
        self.get_hash.setText(_translate("MainWindow", "  HASH"))
